### ISSUE TITLE
Samenwerking

### ISSUE THREAD

**Issue by ghost** [simplyGits/Magister6.php#3]
Hallo Thomas, 
Ik ben bezig met een IOS design. Zou je willen helpen met de recreation van Magister.
Vooral het PHP gedeelte want ik kan het design.

Dit is denk ik de betere Repo.
- Juul

**Comment by tkon99** [comment]
Hi Juul,

Wat wil je? Wil je dat gebruikers inloggen met Magister? Of wil je dat ze hun rooster kunnen bekijken via gepro-osi? Dat is namelijk een wezenlijk verschil. Dit is de Magister communicatie voor PHP. Als je via gepro-osi wilt (dus dat ze alleen een leerlingnummer in moeten voeren) dan moet je hier zijn: https://github.com/tkon99/API-gepro-osi
