### ISSUE TITLE
Probleem!

### ISSUE THREAD

**Issue by Mattiedong** [simplyGits/Magister6.php#4]
Hey!

Ik ben bezig om via whatsapp berichtjes te sturen naar mijn nummer en dat ik dan een appje krijg wanneer ik een nieuw cijfer binnen heb. Alleen ik krijg een error code in de magister6.class.php

Namelijk het volgende:

```
[Wed Dec 02 19:15:01.949869 2015] [:error] [pid 25336] [client 109.200.207.16:58911] PHP Notice:  Trying to get property of non-object in /home/cijfersw/domains/cijfers.web03.prhst.eu/public_html/Magister6.class.php on line 113
```

Dit is de error code die ik krijg. Ik ben dus op zoek gegaan wat er op line 113 en 114 staat en daar staat het volgende:

```
113: if($result->isVerified !== true && $result->state !== "active"){
114: throw new Exception("Magister6.class.php: Session not verified",1);
```

Deze twee regels code komen overeen met mijn error code. Ik vroeg me af of je dit kan fixen!

Alvast bedankt,
Bas

**Comment by tkon99** [comment]
Hi Bas,

Zou je me wat meer informatie over de server zelf kunnen geven. Welke PHP versie, apache versie, etc.

Alvast bedankt,
Thomas

**Comment by Mattiedong** [comment]
Hey,

Dit ga ik even navragen bij mijn webhost, of kan ik dat zelf ook ergens zien?

**Comment by Mattiedong** [comment]
Voor PHP versie 5.6, apache weet ik zo even niet. Is het essentieel dat je dat moet weten? Want apache gebruik ik namelijk helemaal niet.

**Comment by rafaelklaessen** [comment]
Mocht het nog nodig zijn;
Hiermee kun je zien of je server Apache is:
http://whois.domaintools.com/

**Comment by tkon99** [comment]
Gezien de inactiviteit van @Mattiedong sluit ik het topic voorlopig.

@Mattiedong mocht je nog problemen hebben open dan gerust een nieuwe issue.
