### ISSUE TITLE
Probleem met ophalen van roepnaam, achternaam en foto

### ISSUE THREAD

**Issue by splintersuidman** [simplyGits/Magister6.php#5]
Hoi,

Ik ben bezig met het maken van een site die gegevens uit magister kan halen. Maar ik heb een probleempje. Als ik de volgende code heb, krijg ik wel de Magister-versie maar niet de roepnaam, achternaam en foto. (user en pass heb ik vervangen door mijn eigen gebruikersnaam en wachtwoord).

``` PHP
<html>
<body>
<?php
require('lib/Magister6.class.php');
$magister = new Magister("cgu.magister.net", "user", "pass");
// $magister->setSchool('https://cgu.magister.net/');
// $magister->setCredentials("user", "pass");
// $userInfo = $magister->getUserInfo();
// $magister->login();

echo('<h1>'Magister '.$magister->getMagisterInfo()->ProductVersie.'</h1>);

echo('Naam: '.$magister->getUserInfo()->Roepnaam.' '. $magister->getUserInfo()->Achternaam.'<hr>');

echo('<img src="data:image/jpeg;base64,'.$magister->getPicture(200,200,true).'">');

?>
</body>
</html>
```

Als ik

``` PHP
 // $magister->setSchool('https://cgu.magister.net/');
 // $magister->setCredentials("user", "pass");
 // $userInfo = $magister->getUserInfo();
 // $magister->login();
```

zonder `//` gebruik, krijg ik de error 'Session not verified'.

Is mijn code onjuist? Of hoe kan ik het anders oplossen?

Splinter

**Comment by ghost** [comment]
Bij de eerste log je niet in (probeer true als 4e argument toe te voegen
bij de constructor)

Bij de tweede... ik heb dat probleem ook! Magister zegt dat de inlogcodes
niet kloppen, maar als ik het zo'n 10x achter elkaar doe werkt 'ie. (Ik
neem aan dat dat het probleem is, je kan altijd echoen wat je terug krijgt
van Magister om zeker te zijn)

**Comment by splintersuidman** [comment]
Als ik als 4de parameter 'true' toevoeg, krijg ik ook de error 'Session not verified.
Ik denk dat het probleem ligt bij het inloggen. Ook als ik
`$magister->login();`
gebruik krijg ik de error.

**Comment by splintersuidman** [comment]
Hoe bedoel je "als ik het zo'n 10x achter elkaar doe"?
En hoe echo ik alles wat ik van Magister terug krijg?

**Comment by ghost** [comment]
Ik heb de login in een while-loop gezet binnen een trycatch - zodat hij -
als hij faalt - het maximaal 20x probeert. Meestal werkt hij na 10 keer.

**Comment by splintersuidman** [comment]
@Codicassert zou je jouw code kunnen sturen?

**Comment by tkon99** [comment]
Hi allemaal,
Het probleem is bekend bij mij. Het is sinds de laatste magister api update, heb er nog niet naar gekeken. Zal het dit weekend inplannen.

**Comment by splintersuidman** [comment]
@tkon99 oké fijn!

**Comment by tkon99** [comment]
@lieuwex hadden we dit bij magisterjs ook niet?

**Comment by ghost** [comment]
Oh ja, die laatste update zorgt ervoor dat je JSON MOET versturen (i.p.v.)
formdata

**Comment by tkon99** [comment]
Het is trouwens niet verboden om een pull-request te maken :wink:

**Comment by lieuwex** [comment]
@tkon99 We hadden geen problemen met Magister 6.1, maar wel met een eerdere versie. Waarvoor ik de [inlogcode](https://github.com/simplyGits/MagisterJS/blob/c663117511c1fece8acdba6695cc1a2ba1a49ef7/src/Magister.coffee#L743) toen heb aangepast.

**Comment by tkon99** [comment]
@lieuwex Thanks!

**Comment by ghost** [comment]
Was op school, zal als ik thuis ben mijn inlogcode in een PR zetten :P (als
je er niet dan al eentje hebt)

**Comment by ghost** [comment]
https://github.com/simplyGits/Magister6.php/pull/6 PR gemaakt :ok_hand:

**Comment by tkon99** [comment]
Zou nu gefixt moeten zijn. Mocht er iets voorvallen, open dan gerust een nieuwe issue.
